image: docker:stable

services:
  - docker:dind

variables:
    DOCKER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/docker"

cache:
  paths:
  - .cache/docker

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script:
    - test -f "${DOCKER_CACHE_DIR}/cache.tar" && docker load -i "${DOCKER_CACHE_DIR}/cache.tar" || true
    - cd vacation_manager
    - docker build -t vacation_manager .
    - docker save -o "${DOCKER_CACHE_DIR}/cache.tar" $(docker history -q vacation_manager | grep -v '<missing>')
  before_script:
    - mkdir -p $DOCKER_CACHE_DIR
 

DeployMaster:
  only:
    - master
  stage: deploy
  script:
    - docker load -i "${DOCKER_CACHE_DIR}/cache.tar"
    - docker images
    - docker tag vacation_manager aeao93/vacation_manager:latest
    - docker push aeao93/vacation_manager:latest

DeployTag:
  only:
    - tags
  stage: deploy
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_TAG
    - docker push aeao93/vacation_manager:$CI_COMMIT_TAG

DeployCustom:
  stage: deploy
  only:
    - branches
  except:
    - master
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_REF_NAME
    - docker push aeao93/vacation_manager:$CI_COMMIT_REF_NAME
