image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - cd vacation_manager

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build --tag aeao93/vacation_manager .

test:
  stage: test
  script:
    - tests/docker-tests.sh
