image: docker:stable

services:
  - docker:dind

variables:
    DOCKER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/docker"
    VERSION: $(echo "$CI_COMMIT_REF_NAME" | grep -P '\d\.\d\.\d' || date +%Y.%m.%d | sed 's/\.0/./g')
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u aeao93 -p huni1999 || True

cache:
  paths:
  - .cache/docker

stages:
  - build
  - test
  - deploy
  
Build:
  stage: build
  script:
    - test -f "${DOCKER_CACHE_DIR}/cache.tar" && docker load -i "${DOCKER_CACHE_DIR}/cache.tar" || true
    - cd vacation_manager
    - docker build -t vacation_manager .
    - docker save -o "${DOCKER_CACHE_DIR}/cache.tar" $(docker images vacation_manager | sed '1d' | awk '{print $1 ":" $2 }')
    - echo $VERSION
  before_script:
    - mkdir -p $DOCKER_CACHE_DIR
 

Push-Docker-Latest:
  only:
    - master
  stage: deploy
  script:
    - docker load -i "${DOCKER_CACHE_DIR}/cache.tar"
    - docker tag vacation_manager aeao93/vacation_manager:latest
    - docker push aeao93/vacation_manager:latest

Push-Docker-Tag:
  only:
    - tags
  stage: deploy
  script:
    - docker load -i "${DOCKER_CACHE_DIR}/cache.tar"
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_TAG
    - docker push aeao93/vacation_manager:$CI_COMMIT_TAG

Push-Docker-Custom:
  stage: deploy
  only:
    - branches
  except:
    - master
  script:
    - docker load -i "${DOCKER_CACHE_DIR}/cache.tar"
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_REF_NAME
    - docker push aeao93/vacation_manager:$CI_COMMIT_REF_NAME
