image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

stages:
  - build
  - test
  - deploy

 build_image:
   script:
     - tests/docker-tests.sh
     - docker run my-docker-image /script/to/run/tests