image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

cache:
  paths:
  - $HOME/.cache/docker

Build:
  stage: build
  script:
    - test -f "$HOME/.cache/docker/cache.tar" && docker load -i "$HOME/.cache/docker/cache.tar" || true
    - cd vacation_manager
    - docker build --tag vacation_manager .
    - docker save -o "$HOME/.cache/docker/cache.tar" $(docker history -q vacation_manager | grep -v '<missing>')

DeployMaster:
  only:
    - master
  stage: deploy
  script:
    - docker load -i "$$HOME/.cache/docker/cache.tar"
    - docker tag vacation_manager aeao93/vacation_manager:latest
    - docker push aeao93/vacation_manager:latest

DeployTag:
  only:
    - tags
  stage: deploy
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_TAG
    - docker push aeao93/vacation_manager:$CI_COMMIT_TAG

DeployCustom:
  stage: deploy
  only:
    - branches
  except:
    - master
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_REF_NAME
    - docker push aeao93/vacation_manager:$CI_COMMIT_REF_NAME
