image: docker:stable

services:
  - docker:dind
  
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script:
    - cd vacation_manager
    - docker build --tag vacation_manager .

# Test:
#   stage: test
#   script:
#     - echo "HELLO WORLD"

DeployMaster:
  services: 
    - vacation_manager
  only:
    - master
  stage: deploy
  script:
    - docker tag vacation_manager aeao93/vacation_manager:latest
    - docker push aeao93/vacation_manager:latest

DeployTag:
  only:
    - tags
  stage: deploy
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_TAG
    - docker push aeao93/vacation_manager:$CI_COMMIT_TAG

DeployCustom:
  stage: deploy
  only:
    - branches
  except:
    - master
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_REF_NAME
    - docker push aeao93/vacation_manager:$CI_COMMIT_REF_NAME
