image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker info
  - cd vacation_manager

Test:
  stage: test
  script:
    - echo "HELLO WORLD"

PUSH_MASTER:
  only:
    - master
  stage: deploy
  script:
    - docker tag vacation_manager aeao93/vacation_manager:latest
    - docker push aeao93/vacation_manager:latest

PUSH_TAG:
  only:
    - tags
  stage: deploy
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_TAG
    - docker push aeao93/vacation_manager:$CI_COMMIT_TAG

PUSH_CUSTOM:
  stage: deploy
  only:
    - branches
  except:
    - master
  script:
    - docker tag vacation_manager aeao93/vacation_manager:$CI_COMMIT_REF_NAME
    - docker push aeao93/vacation_manager:$CI_COMMIT_REF_NAME
