sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - docker pull aeao93/vacation_manager || true

script:
  - docker build --tag aeao93/vacation_manager .
  - ./tests/docker-tests.sh --image vacation_manager:testing

after_success:
  - docker push aeao93/vacation_manager:latest
  - docker push aeao93/vacation_manager:1.0