sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - cd vacation_manager
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS

script:
  - docker build --tag aeao93/vacation_manager .
  - ./tests/docker-tests.sh

after_success:
  - docker tag aeao93/vacation_manager:latest aeao93/vacation_manager:beta
  - docker push aeao93/vacation_manager
  - docker logout

after_success:
    - if [ "$TRAVIS_TAG" ]; then
          docker tag aeao93/vacation_manager aeao93/vacation_manager:$TRAVIS_TAG;
          docker push flywheel/reaper:$TRAVIS_TAG;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" == "master" ]; then
          docker tag aeao93/vacation_manager aeao93/vacation_manager:latest;
          docker push aeao93/vacation_manager:latest;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" != "master" ]; then
          docker tag aeao93/vacation_manager aeao93/vacation_manager:$TRAVIS_BRANCH.latest;
          docker push aeao93/vacation_manager:$TRAVIS_BRANCH.latest;
      fi
