sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - docker login -u aeao93 -p huni1999

script:
  - cd vacation_manager
  - docker build -t aeao93/vacation_manager .

after_success:
  - docker tag aeao93/vacation_manager:latest aeao93/vacation_manager:beta

after_success:
    - echo bela
    - if [ "$TRAVIS_TAG" ]; then
          docker tag aeao93/vacation_manager aeao93/vacation_manager:$TRAVIS_TAG;
          docker push aeao93/vacation_manager:$TRAVIS_TAG;
      elif [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" == "master" ]; then
          docker tag aeao93/vacation_manager aeao93/vacation_manager:latest;
          docker push aeao93/vacation_manager:latest;
      elif [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" != "master" ]; then
          docker tag aeao93/vacation_manager aeao93/vacation_manager:$TRAVIS_BRANCH.latest;
          docker push aeao93/vacation_manager:$TRAVIS_BRANCH.latest;
      fi
