sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS

script:
  - cd vacation_manager
  - docker build -t test/vacation_manager .

after_success:
  - docker tag test/vacation_manager:latest test/vacation_manager:beta

after_success:
    - if [ "$TRAVIS_TAG" ]; then
          docker tag test/vacation_manager test/vacation_manager:$TRAVIS_TAG;
          docker push flywheel/reaper:$TRAVIS_TAG;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" == "master" ]; then
          docker tag test/vacation_manager test/vacation_manager:latest;
          docker push test/vacation_manager:latest;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" != "master" ]; then
          docker tag test/vacation_manager test/vacation_manager:$TRAVIS_BRANCH.latest;
          docker push test/vacation_manager:$TRAVIS_BRANCH.latest;
      fi
