sudo: required

language: python

services:
  - docker

install:
  - docker build --tag aeao93/vacation_manager .
  - docker run -p 4000:80 aeao93/vacation_manager

script:
  - docker ps | grep -q vacation_manager