sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - version="$(awk '$2 == "VACATION_MANAGER_SERVICE_VERSION" { print $3; exit }' Dockerfile)"
  - docker pull aeao93/vacation_manager || true

script:
  - docker build --tag aeao93/vacation_manager .

deploy:
  provider: script
  script: docker push "aeao93/vacation_manager:latest" && docker push "aeao93/vacation_manager:${version}"
  on:
    branch: master