sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - docker pull aeao93/vacation_manager || true

script:
  - docker build -t vacation_manager .

after_success:
    - if [ "$TRAVIS_TAG" ]; then
          docker tag vacation_manager aeao93/vacation_manager:$TRAVIS_TAG;
          docker push flywheel/reaper:$TRAVIS_TAG;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" == "master" ]; then
          docker tag vacation_manager aeao93/vacation_manager:latest;
          docker push aeao93/vacation_manager:latest;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" != "master" ]; then
          docker tag vacation_manager aeao93/vacation_manager:$TRAVIS_BRANCH.latest;
          docker push aeao93/vacation_manager:$TRAVIS_BRANCH.latest;
      fi
