sudo: required

language: python
python:
  - '3.6'

services:
  - docker

before_script:
  - docker pull aeao93/vacation_manager || true

script:
  - docker build --tag aeao93/vacation_manager .

deploy:
  provider: script
  script: docker push aeao93/vacation_manager
  on:
    branch: master