sudo: required

language: python

services:
  - docker

before_script:
  - docker pull aeao93/vacation_manager || true
  - docker build --tag aeao93/vacation_manager .

script:
  - docker ps | grep -q vacation_manager